name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install --cask docker
    
    - name: Start Docker
      run: |
        open /Applications/Docker.app
        # Wait for Docker to start
        while ! docker system info > /dev/null 2>&1; do
          echo "Waiting for Docker to start..."
          sleep 5
        done

    - name: Verify Docker installation
      run: docker --version
    
    - name: Build Docker image
      run: docker build -t prototype .

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app prototype make install

    - name: Run tests
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app prototype make test

    - name: Clean up
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app prototype make clean
