name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install Docker
      run: |
        brew install --cask docker
        open /Applications/Docker.app
        while ! docker system info > /dev/null 2>&1; do
          echo "Waiting for Docker to start..."
          sleep 5
        done
        docker --version
    
    - name: Build Docker image
      run: docker build -t prototype .

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app prototype make install

    - name: Run tests
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app prototype make test

    - name: Clean up
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app prototype make clean
