name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Docker
      run: |
        sudo apt-get remove -y containerd
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Build Docker image
      run: docker build -t prototype .

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app prototype make install

    - name: Run tests
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app prototype make test

    - name: Clean up
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app prototype make clean
